### PR TITLE
Removed anonymous 'wb' variable from labelled fxs to fix NOTE - MH

### PR DESCRIPTION
**Pull request by Meghansaha**
accidentally touched .rprofile, but changes made with globals.r to silence the note during devtool's check()

### CODE REVIEW

**Comment by ddsjoberg** [comment]
I think this will need a different solution that addresses the underlying messaging, rather than silencing it. Let's chat details !

**Comment by Meghansaha** [comment]
😂😅 absolutely. I can dig in deeper to this as well

**Comment by Meghansaha** [comment]
Updated with Daniel's suggesting. Awaiting review from @shannonpileggi . Can't assign for some reason.

**Review by shannonpileggi — COMMENTED** [review]
This looks great! Thank you! The only thing I am wondering about the `labelled_sheet` function, which the documentation says is a hidden function but appears to be exported. Which do you think it should be?

**Comment by Meghansaha** [comment]
I think @ddsjoberg were both confused on that too (because it seems similar to `add_labelled_sheet` we werent sure how these two worked together/ were similar, etc.

**Comment by ddsjoberg** [comment]
1. add `@noRd` tag to the un-exported function
2. move argument descriptions to `add_labelled_sheet()` and no longer use `@inheritParams`
3. re-document, and re-test

**Review by shannonpileggi — APPROVED** [review]
Looks great, thank you!

**Pull request merged**
